# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/example-maven-travis
    
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
    
      - checkout
      
      - run: mvn package

      - run: sudo su -c 'echo "deb http://deb.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'
      - run: sudo rm -rf /var/lib/apt/lists/*
      - run: sudo apt-get update
      - run: sudo apt install -t jessie-backports  openjdk-8-jre-headless ca-certificates-java

      - run: bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)

